namespace TcpDotNet;

/// <summary>
///     Represents the method that will handle an asynchronous event that has no event data.
/// </summary>
/// <param name="sender">The source of the event.</param>
/// <param name="e">An object that contains no event data.</param>
public delegate Task AsyncEventHandler(object? sender, EventArgs e);

/// <summary>
///     Represents the method that will handle an asynchronous event when the event provides data.
/// </summary>
/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
/// <param name="sender">The source of the event.</param>
/// <param name="e">An object that contains event data.</param>
public delegate Task AsyncEventHandler<in TEventArgs>(object? sender, TEventArgs e);
